// <auto-generated />
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Api.data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Api.Entities.Deltagare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adress")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Efternamn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Epost")
                        .HasColumnType("TEXT");

                    b.Property<string>("Förnamn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mobilnummer")
                        .HasColumnType("TEXT");

                    b.Property<int>("PostalCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StateProvince")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Deltagare");
                });

            modelBuilder.Entity("Api.Entities.Kurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kursbeskrivning")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kurslängd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kursnummer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kurstitel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nivå")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kurser");
                });
#pragma warning restore 612, 618
        }
    }
}
